//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddUsersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int IdUser { get; set; }
        public int IdGroupUser { get; set; }
        public string UserName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public string Passport { get; set; }
        public string Tel { get; set; }
        public string Address { get; set; }
        public string INN { get; set; }
        public string Mail { get; set; }
        public bool Enabled { get; set; }
        public string Country { get; set; }
        public bool Visible { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string City { get; set; }
        public string InfoPoint { get; set; }
        public string ChildName1 { get; set; }
        public string ChildName2 { get; set; }
        public string ChildName3 { get; set; }
        public Nullable<System.DateTime> ChildBirthday1 { get; set; }
        public Nullable<System.DateTime> ChildBirthday2 { get; set; }
        public Nullable<System.DateTime> ChildBirthday3 { get; set; }
        public int SareaId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> SareaIdActive { get; set; }
        public Nullable<System.DateTime> WhenShowBirthday1 { get; set; }
        public Nullable<System.DateTime> WhenShowBirthday2 { get; set; }
        public Nullable<System.DateTime> WhenShowBirthday3 { get; set; }
        public Nullable<System.DateTime> DateProfile { get; set; }
        public Nullable<int> IdCashier { get; set; }
        public Nullable<System.DateTime> Birthday2 { get; set; }
        public string LastName2 { get; set; }
        public string Mail2 { get; set; }
        public string Patronymic2 { get; set; }
        public string Tel2 { get; set; }
        public string UserName2 { get; set; }
        public string ClientCode { get; set; }
        public Nullable<bool> ClientCodeActivate { get; set; }
        public string ClientCodeSite { get; set; }
        public Nullable<bool> ClientCodeSiteActivate { get; set; }
        public Nullable<bool> DefaultUser { get; set; }
        public string ViberTel { get; set; }
    }
}
