//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirstTutorial
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sareas
    {
        public int SareaId { get; set; }
        public string SareaName { get; set; }
        public Nullable<int> User_UserId { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
